<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
    <!ELEMENT deportistas (deportista+)>
    <!ELEMENT deportista (deporte, nombre)>
    <!ELEMENT deporte (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
]>
<deportistas>
    <deportista>
        <deporte>
            atletismo
        </deporte>
        <nombre>
            Jesse Owens
        </nombre>
    </deportista>
    <deportista>
        <deporte>
            nataci√≥n
        </deporte>
        <nombre>
            Mark Spitz
        </nombre>
    </deportista>
</deportistas>
